name: google_keep_clone_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  go_router: ^12.0.0
  hooks_riverpod: ^2.4.4
  readmore: ^2.2.0
  riverpod: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: google
      fonts:
        - asset: assets\fonts\google sans\ProductSans-Black.ttf
          weight: 100
        - asset: assets\fonts\google sans\ProductSans-BlackItalic.ttf
          weight: 200
        - asset: assets\fonts\google sans\ProductSans-Bold.ttf
          weight: 300
        - asset: assets\fonts\google sans\ProductSans-BoldItalic.ttf
          weight: 400
        - asset: assets\fonts\google sans\ProductSans-Italic.ttf
          weight: 500
        - asset: assets\fonts\google sans\ProductSans-Light.ttf
          weight: 600
        - asset: assets\fonts\google sans\ProductSans-LightItalic.ttf
          weight: 700
        - asset: assets\fonts\google sans\ProductSans-Medium.ttf
          weight: 800
        - asset: assets\fonts\google sans\ProductSans-MediumItalic.ttf
          weight: 900
        - asset: assets\fonts\google sans\ProductSans-Regular.ttf
          weight: 900
        - asset: assets\fonts\google sans\ProductSans-Thin.ttf
          weight: 900
        - asset: assets\fonts\google sans\ProductSans-ThinItalic.ttf
          weight: 900
        

  assets:
    - assets\icons\icons8-plus-100-removebg-preview.png
    - assets\images\download.jpg
    